---
title: "wids_dataXB_eda"
team: "Data XB"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library-packages}
library(tidyverse)
library(patchwork)
library(dplyr)
```

```{r read-dataset}
#a csv file on every variable's meaning
varDict <- read.csv("widsdatathon2021/DataDictionaryWiDS2021.csv") 

#EDA this dataset
Diabetes <- read.csv("widsdatathon2021/TrainingWiDS2021.csv") 

```

###EDA Question & TO DOs
What are the missing values and their percentage in each column?
  -How values should we use to fill in the NAs?
What are variables related to diabetes?
  -Every BMI-related variables?
  -Ethnicity?Age?
  -Do we use every chemical variables (albumin, calcium...) in our model?
What columns can we drop? 
  -every ID
  

```{r glimpse-dataset}
glimpse(Diabetes)
```

```{r missing-in-each-column}
colMeans(is.na(Diabetes))%>%
  kable()
```

```{r diabetes_by_gender}
Diabetes%>%
  filter(!is.na(gender))%>%
  ggplot(aes(x = gender, fill = factor(diabetes_mellitus)))+
  geom_bar(position = "fill")
```

